---
title: "HW1"
author: "Minzhe Zhang"
date: "2018/1/21"
output: html_document
---

### 1. Question 1
#### (a) part i
```{r}
### (i)
Y <- c(16,9,17,12,22,13,8,15,19,11)
X <- c(1,0,2,0,3,1,0,1,2,0)
lm.model <- lm(Y ~ X)
summary(lm.model)
plot(X, Y)
abline(lm.model)
res.mat <- as.matrix(lm.model$residuals)
X.mat <- as.matrix(data.frame(X0 = rep(1,10), X = X))
t(res.mat) %*% X.mat
plot(lm.model)

### (ii)
Y.pred.lm <- predict(lm.model, newdata = data.frame(X = c(0,1,2,3)))
Y.pred.lm

### (iii)
lm.model$coefficients[2]
```

#### (b) part ii
```{r}
### (i)
pois.model <- glm(Y ~ X, family = poisson(link = "log"))
summary(pois.model)

### (ii)
Y.pred.pois <- predict(pois.model, type = "response", newdata = data.frame(X = c(0,1,2,3)))
data.frame(Y.pred.lm, Y.pred.pois)

### (iii)
plot(X, Y)
abline(lm.model, col = "red")
lines(seq(0,3,0.1), predict(pois.model, type = "response", newdata = data.frame(X = seq(0,3,0.1))), col = "blue")
legend("bottomright", legend = c("lm", "poisson"), col = c("red", "blue"), lty = 1)

### (iv)
lambda <- predict(pois.model, data.frame(X = 0), type = "response")
ppois(10, lambda = lambda)

### (v)
confint(pois.model)
```
